@startuml


package "StarCraft" {

abstract class Race {
종족선택()
}
'종족

'선택된종족
abstract class Terran extends Race {
체력
}
abstract class Zerg extends Race {
체력
자동체력회복()
}
abstract class Protoss extends Race {
방어막
체력
자동방어막회복()
}

'테란유닛
abstract class TerranUnit extends Terran{}
'테란빌딩
abstract class TerranBuilding extends Terran{
건물띄우기(self)
수리하기(SCV, 미네랄)
}

'저그유닛
abstract class ZergUnit extends Zerg {
}
'저그빌딩
abstract class ZergBuilding extends Zerg{
}

'프로토스유닛
abstract class ProtossUnit extends Protoss {
}
'프로토스빌딩
abstract class ProtossBuilding extends Protoss{
}


'인터페이스
interface Bionic {}
interface Mechanic {}
interface Attack {}
'interface Alien {}

' 유닛생성
' 1. 테란
class Marine extends TerranUnit{}
class Medic extends TerranUnit{
힐({테란유닛(바이오닉),SCV})
힐(프로토스유닛(바이오닉))
}
class Tank extends TerranUnit{
}
class Vulture extends TerranUnit{
}
class Scv extends TerranUnit{
미네랄캐기(미네랄)
수리하기(메카닉, 테란빌딩)
}

'2. 저그
class Zergling extends ZergUnit {}

'a. 바이오닉 연결
class Marine implements Bionic{}
class Medic implements Bionic{}
class Zealot implements Bionic{}
abstract Zerg implements Bionic{}
class Hydralisk extends ZergUnit {}

'3. 프로토스
class Zealot extends ProtossUnit {}
class Dargoon extends ProtossUnit {}

'b. 메카닉 연결
class Vulture implements Mechanic{}
class Scv implements Mechanic{}
class Tank implements Mechanic{}
class Dragoon implements Mechanic{}

'<i. 공격>
class Scv implements Attack{}
class Marine implements Attack{}
class Tank implements Attack{}
class Vulture implements Attack{}

class Zealot implements Attack{}
class Dargoon implements Attack{}

class Zergling implements Attack{}
class Hydralisk implements Attack{}



' class Attack implements UnitGroup{}
' class Mechanic implements UnitGroup{}
' class Bionic implements UnitGroup{}

abstract class TerranUnit implements UnitGroup{
}
abstract class ZergUnit implements UnitGroup{
}
abstract class ProtossUnit implements UnitGroup{
}


interface UnitGroup {
이동()
}
}
@enduml
