@startuml

abstract class Animal {
+ type
+ name
+ sound
+ makeSound()
}

class Dog extends Animal implements loveWalking {

}

class Cat extends Animal {
+ punch()
}

class Person implements loveWalking {

}

interface loveWalking {
+ walking()
}

@enduml