@startuml

scale 1.5

abstract class Animal {
    String sound
    String name

    void makeSound()
}

class Dog extends Animal implements 산책맨 {
}

'extends 상속
class Cat extends Animal {
    void punch()
}

'implements 구현
class Person implements 산책맨 {

}

'abstract interface class
interface 산책맨 {
    void 산책()
}

@enduml