@startuml

scale 1.5

abstract class Asset{
}

abstract class TangibleAsset extends Asset {
  String name;
  int price;
  String color;
}

class Book extends TangibleAsset {

  String isbn;

}

class Computer extends TangibleAsset {
 String makerName;

}


class IntangibleAsset{
}

class patent extends IntangibleAsset{
}



@enduml