@startuml

abstract class TangibleAsset {
  String name
  int price
  String color
  void touchAble()
}

class Book extends TangibleAsset {
  String isbn
}

class Computer extends TangibleAsset{
  String makerName
}
@enduml