@startuml
'https://plantuml.com/class-diagram

interface X {
  +a();
}

abstract class Y implements X {
  +b();
}

class A extends Y {
  +a() // @override

  +b() // @override

  +c()
}

class B extends Y {
  +a() // @override

  +b() // @override

  +c()
}




@enduml