@startuml Asset 
scale 1
abstract class Asset {
  +String name
  +int price  
}
abstract class TangibleAsset extends Asset implements Thing{
  +String color

}
class InTangibleAsset extends Asset {
  +int period
  +String field

}
class Patent extends InTangibleAsset {
  +String jurisdictionDepartment
  +String jurisdictionPerson

}
class Book extends TangibleAsset implements Thing {
  +String isbn
  +double _weight;

  +set weight(double value) {}
  +double get weight();
}
class Computer extends TangibleAsset implements Thing {
  +String makerName
  +double _weight;

  +set weight(double value) {}
  +double get weight();
}
class Stone implements Thing {  
  +double _weight;

  +set weight(double value) {}
  +double get weight();
}
interface Thing {
  +set weight(double value) 
  +double get weight()
}
@enduml