@startuml
'https://plantuml.com/class-diagram
class Point{
    double x;
    double y;
}

class Rectangle extends Point{

    final Point topLeft;
    final Point bottomRight;

    double get width(){
        return bottomRight.x - (topLeft.x);}

    double getRound() {
        double result = 2 * (width + height);
        return result;
    }
}

@enduml