@startuml

abstract class Asset {
}

abstract class IntangibleAsset extends Asset{
String patent
}

abstract class TangibleAsset extends Asset{
String name
String color
int price
}

class book extends TangibleAsset {
+ String isbn
}

class Computer extends TangibleAsset {
+ String makerName
}

@enduml