@startuml
'https://plantuml.com/class-diagram

class Animal {
    String type;
    String sound;
}

class Cat extends Animal {
    void grooming(){}
}

class Bird extends Animal {
    void fly() {}
}

class dog extends Animal {
    void bark() {}
}

class human extends Animal {
    void useLanguage(){}
}

@enduml