@startuml Asset



abstract class Asset{
    +String name
    +int price
}

interface Thing{
     +get()
     +set()
}


abstract class TangibleAsset extends Asset implements Thing{
    +String color
}
class Book extends Asset{

    +String isbn
}

class computer extends Asset{

    +String makerName
}




@enduml