const _baseUrl = 'https://jsonplaceholder.typicode.com';
const todosUrl = '$_baseUrl/todos';
const commentsUrl = '$_baseUrl/comments';
const albumsUrl = '$_baseUrl/albums';
const photosUrl = '$_baseUrl/photos';
const postsUrl = '$_baseUrl/posts';
const usersUrl = '$_baseUrl/users';
const maskUrl = 'http://104.198.248.76:3000/mask';
const movieBaseUrl = 'https://api.themoviedb.org/3/movie';
const movieListUrl = '$movieBaseUrl/upcoming?$movieQueryParam';
const movieQueryParam = '$movieApiKey&language=ko-KR';
const movieApiKey = 'api_key=a64533e7ece6c72731da47c9c8bc691f';
const fakeMovieInfoUrl = '$movieBaseUrl/957304?$movieQueryParam&page=1';
const pixabayUrl='https://pixabay.com/api/';
const pixabayUserKey='3565685-4273f3b245457492a768921ad';
