@startuml Rectangle

class RectanglePoint {
  +Point bottomLeft;
  +Point topRight;

  +RectanglePoint(this.bottomLeft, this.topRight);
  +int area()
  +int round()
  
}

class Point {
  -int _x;
  -int _y;

  +Point(this._x, this._y);
}
RectanglePoint <|-- Point
@enduml