@startuml Book

class Book {
  +String title;
  +String author;
  +String genre;

  +Book(this.title, this.author,this.genre );
}


class Fictoon extends Book {
  +String subgenre;
  +Fictoon(super.title, super.author, super.genre, this.subgenre);
}

class NonFictoon extends Book {
  
  +String subject;
  +NonFictoon(super.title, super.author, super.genre, this.subject);
}

@enduml