@startuml
'https://plantuml.com/sequence-diagram

class Asset{
    name()
    price()
}

abstract class TangibleAsset extends Asset implements Thing{
    +name()
    +price()
    -color
    ++weight;

}
class Book extends TangibleAsset
{
    +name()
    +price()
    -color
    ++weight;
     isbn()
}
class Computer extends TangibleAsset
{
    +name()
    +price()
    -color
    ++weight;
    makerName
}

abstract class Intangibleasset extends Asset
{
    +name()
    +price()
    -type

}

class CopyRight extends Intangibleasset
{
    +name()
    +price()
    -type
    characteristic
    }


class Trademark extends Intangibleasset{
  +name()
  +price()
  -type
}

interface Thing{
    weight;
}



@enduml