@startuml
'https://plantuml.com/class-diagram

class Hero {
    double hp = 100;
    int mp = 100;
}

class Slime {
    int hp = 50;
    final String suffix;

    void attack(Hero hero){}
}

class PoisonSlime extends Slime{
    int numberOfPoisonAttack = 5;

    @override
    void attack(Hero hero) {}
}
@enduml